---
- name: Install EMQX
  ansible.builtin.include_tasks: install.yml
  tags:
    - install

- name: Configure EMQX
  ansible.builtin.include_tasks: config.yml
  tags:
    - configure

- name: Tune EMQX
  ansible.builtin.include_tasks: tuning.yml
  tags:
    - tune
  when: emqx_tune_service | bool
