---
- name: "Load required modules"
  community.general.modprobe:
      name:
        - ip_conntrack
        - nf_conntrack
      state: present
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int <= 18

- name: "Linux kernel tuning"
  block:
    - name: Tune max opened file handles limit (fs.file-max)
      ansible.posix.sysctl:
        name: fs.file-max
        value: "{{ emqx_max_opened_file_handles }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune maximum number of opened file handles (fs.nr_open)
      ansible.posix.sysctl:
        name: fs.nr_open
        value: "{{ emqx_max_opened_file_handles }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes

- name: "Network tuning"
  block:
    - name: Tune the size of the incoming connections backlog (net.core.somaxconn). 
      ansible.posix.sysctl:
        name: net.core.somaxconn
        value: "{{ emqx_net_core_somaxconn }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune the size of the incoming connections backlog (net.ipv4.tcp_max_syn_backlog).
      ansible.posix.sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: "{{ emqx_net_ipv4_tcp_max_syn_backlog }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune the size of the incoming connections backlog (net.core.netdev_max_backlog).
      ansible.posix.sysctl:
        name: net.core.netdev_max_backlog
        value: "{{ emqx_net_core_netdev_max_backlog }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune IPv4 local port range (net.ipv4.ip_local_port_range).
      ansible.posix.sysctl:
        name: net.ipv4.ip_local_port_range
        value: emqx_net_ipv4_ip_local_port_range
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TCP Socket memory buffer (net.core.rmem_default).
      ansible.posix.sysctl:
        name: net.core.rmem_default
        value: "{{ emqx_net_core_rmem_default }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TCP Socket memory buffer (net.core.wmem_default).
      ansible.posix.sysctl:
        name: net.core.wmem_default
        value: "{{ emqx_net_core_wmem_default }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TCP Socket memory buffer (net.core.rmem_max).
      ansible.posix.sysctl:
        name: net.core.rmem_max
        value: "{{ emqx_net_core_rmem_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TCP Socket memory buffer (net.core.wmem_max).
      ansible.posix.sysctl:
        name: net.core.wmem_max
        value: "{{ emqx_net_core_wmem_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TCP Socket memory buffer (net.core.optmem_max).
      ansible.posix.sysctl:
        name: net.core.optmem_max
        value: "{{ emqx_net_core_optmem_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TCP Socket Read memory buffer (emqx_net_ipv4_tcp_rmem).
      ansible.posix.sysctl:
        name: net.ipv4.tcp_rmem
        value: "{{ emqx_net_ipv4_tcp_rmem }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TCP Socket Write memory buffer (net.ipv4.tcp_wmem).
      ansible.posix.sysctl:
        name: net.ipv4.tcp_wmem
        value: "{{ emqx_net_ipv4_tcp_wmem }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune maximum size of the connection tracking table (net.nf_conntrack_max).
      ansible.posix.sysctl:
        name: net.nf_conntrack_max
        value: "{{ emqx_net_nf_conntrack_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune maximum size of netfilter connection tracking table (net.netfilter.nf_conntrack_max).
      ansible.posix.sysctl:
        name: net.netfilter.nf_conntrack_max
        value: "{{ emqx_net_netfilter_nf_conntrack_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TCP Conenction tracking timeout (net.netfilter.nf_conntrack_tcp_timeout_time_wait).
      ansible.posix.sysctl:
        name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
        value: "{{ emqx_net_netfilter_nf_conntrack_tcp_timeout_time_wait }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune TIME-WAIT Bucket Pool, Recycing and Reuse (net.ipv4.tcp_max_tw_buckets).
      ansible.posix.sysctl:
        name: net.ipv4.tcp_max_tw_buckets
        value: "{{ emqx_net_ipv4_tcp_max_tw_buckets }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - name: Tune timeout for FIN-WAIT-2 Sockets (net.ipv4.tcp_fin_timeout).
      ansible.posix.sysctl:
        name: net.ipv4.tcp_fin_timeout
        value: "{{ emqx_net_ipv4_tcp_fin_timeout }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
