---
- name: "Load required modules"
  ansible.builtin.modprobe:
      name:
        - ip_conntrack
        - nf_conntrack
      state: present

- name: "Linux kernel tuning"
  block:
    - ansible.builtin.sysctl:
        name: fs.file_max
        value: "{{ emqx_max_opened_file_handles }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: fs.nr_open
        value: "{{ emqx_max_opened_file_handles }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes

- name: "Network tuning"
  block:
    - ansible.builtin.sysctl:
        name: net.core.somaxconn
        value: "{{ emqx_net_core_somaxconn }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: "{{ emqx_net_ipv4_tcp_max_syn_backlog }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.core.netdev_max_backlog
        value: "{{ emqx_net_core_netdev_max_backlog }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.ipv4.ip_local_port_range
        value: "{{ emqx_net_ipv4_ip_local_port_range }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.core.rmem_default
        value: "{{ emqx_net_core_rmem_default }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.core.wmem_default
        value: "{{ emqx_net_core_wmem_default }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.core.rmem_max
        value: "{{ emqx_net_core_rmem_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.core.wmem_max
        value: "{{ emqx_net_core_wmem_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.core.optmem_max
        value: "{{ emqx_net_core_optmem_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.ipv4.tcp_rmem
        value: "{{ emqx_net_ipv4_tcp_rmem }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.ipv4.tcp_wmem
        value: "{{ emqx_net_ipv4_tcp_wmem }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.nf_conntrack_max
        value: "{{ emqx_net_nf_conntrack_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.netfilter.nf_conntrack_max
        value: "{{ emqx_net_netfilter_nf_conntrack_max }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
        value: "{{ emqx_net_netfilter_nf_conntrack_tcp_timeout_time_wait }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.ipv4.tcp_max_tw_buckets
        value: "{{ emqx_net_ipv4_tcp_max_tw_buckets }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
    - ansible.builtin.sysctl:
        name: net.ipv4.tcp_fin_timeout
        value: "{{ emqx_net_ipv4_tcp_fin_timeout }}"
        sysctl_set: yes
        state: present
        sysctl_file: "/etc/sysctl.conf"
        reload: yes
