---
name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test Role
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: Run Molecule tests
        uses: onaio/molecule-action@master
